# Generated by Django 3.1.7 on 2021-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('price_difference', '-created')},
        ),
        migrations.AlterField(
            model_name='link',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
